/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../..";
import * as PromptonApi from "../../../../../api";
import * as core from "../../../../../core";
export declare const OrgUpdate: core.serialization.Schema<serializers.OrgUpdate.Raw, PromptonApi.OrgUpdate>;
export declare namespace OrgUpdate {
    interface Raw {
        name?: string | null;
        access_keys?: Record<string, string> | null;
    }
}
