/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as PromptonApi from "../../api";
import * as core from "../../core";
export declare const ApiStatusResponse: core.serialization.ObjectSchema<serializers.ApiStatusResponse.Raw, PromptonApi.ApiStatusResponse>;
export declare namespace ApiStatusResponse {
    interface Raw {
        version: string;
        message: string;
        dbstatus: serializers.DbStatus.Raw;
        github_sha?: string | null;
        github_env?: string | null;
    }
}
