/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as PromptonApi from "../../api";
import * as core from "../../core";
export declare const BodyGetAccessTokenExtendedTokenPost: core.serialization.ObjectSchema<serializers.BodyGetAccessTokenExtendedTokenPost.Raw, PromptonApi.BodyGetAccessTokenExtendedTokenPost>;
export declare namespace BodyGetAccessTokenExtendedTokenPost {
    interface Raw {
        grant_type?: string | null;
        username: string;
        password: string;
        scope?: string | null;
        client_id?: string | null;
        client_secret?: string | null;
    }
}
