/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as PromptonApi from "../../api";
import * as core from "../../core";
export declare const ChatGptChatCompletitionConfigStop: core.serialization.Schema<serializers.ChatGptChatCompletitionConfigStop.Raw, PromptonApi.ChatGptChatCompletitionConfigStop>;
export declare namespace ChatGptChatCompletitionConfigStop {
    type Raw = string[] | string;
}
