/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as PromptonApi from "../../api";
import * as core from "../../core";
export declare const ChatGptChatCompletitionRequestStop: core.serialization.Schema<serializers.ChatGptChatCompletitionRequestStop.Raw, PromptonApi.ChatGptChatCompletitionRequestStop>;
export declare namespace ChatGptChatCompletitionRequestStop {
    type Raw = string[] | string;
}
