/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as PromptonApi from "../../api";
import * as core from "../../core";
export declare const ChatGptTokenUsage: core.serialization.ObjectSchema<serializers.ChatGptTokenUsage.Raw, PromptonApi.ChatGptTokenUsage>;
export declare namespace ChatGptTokenUsage {
    interface Raw {
        prompt_tokens: number;
        completion_tokens: number;
        total_tokens: number;
    }
}
