/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as PromptonApi from "../../api";
import * as core from "../../core";
export declare const ChatGptCompletitionChoice: core.serialization.ObjectSchema<serializers.ChatGptCompletitionChoice.Raw, PromptonApi.ChatGptCompletitionChoice>;
export declare namespace ChatGptCompletitionChoice {
    interface Raw {
        message: serializers.ChatGptMessage.Raw;
        finish_reason: string;
        index: number;
    }
}
