/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as PromptonApi from "../../api";
import * as core from "../../core";
export declare const ChatGptChatCompletitionResponse: core.serialization.ObjectSchema<serializers.ChatGptChatCompletitionResponse.Raw, PromptonApi.ChatGptChatCompletitionResponse>;
export declare namespace ChatGptChatCompletitionResponse {
    interface Raw {
        id: string;
        object: string;
        created: number;
        model: string;
        usage: serializers.ChatGptTokenUsage.Raw;
        choices: serializers.ChatGptCompletitionChoice.Raw[];
    }
}
