/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as PromptonApi from "../../api";
import * as core from "../../core";
export declare const ChatGptMessage: core.serialization.ObjectSchema<serializers.ChatGptMessage.Raw, PromptonApi.ChatGptMessage>;
export declare namespace ChatGptMessage {
    interface Raw {
        role: serializers.ChatGptRole.Raw;
        content: string;
        name?: string | null;
    }
}
