/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as PromptonApi from "../../api";
import * as core from "../../core";
export declare const ChatGptChatCompletitionConfig: core.serialization.ObjectSchema<serializers.ChatGptChatCompletitionConfig.Raw, PromptonApi.ChatGptChatCompletitionConfig>;
export declare namespace ChatGptChatCompletitionConfig {
    interface Raw {
        model?: string | null;
        temperature?: number | null;
        top_p?: number | null;
        stop?: serializers.ChatGptChatCompletitionConfigStop.Raw | null;
        max_tokens?: number | null;
        presence_penalty?: number | null;
        frequency_penalty?: number | null;
        logit_bias?: Record<string, number> | null;
    }
}
