/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as PromptonApi from "../../api";
import * as core from "../../core";
export declare const ChatGptChatCompletitionRequest: core.serialization.ObjectSchema<serializers.ChatGptChatCompletitionRequest.Raw, PromptonApi.ChatGptChatCompletitionRequest>;
export declare namespace ChatGptChatCompletitionRequest {
    interface Raw {
        model?: string | null;
        temperature?: number | null;
        top_p?: number | null;
        stop?: serializers.ChatGptChatCompletitionRequestStop.Raw | null;
        max_tokens?: number | null;
        presence_penalty?: number | null;
        frequency_penalty?: number | null;
        logit_bias?: Record<string, number> | null;
        messages: serializers.ChatGptMessage.Raw[];
        n?: number | null;
        stream?: boolean | null;
        user?: string | null;
    }
}
