/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as PromptonApi from "../../api";
import * as core from "../../core";
export declare const DbStatus: core.serialization.ObjectSchema<serializers.DbStatus.Raw, PromptonApi.DbStatus>;
export declare namespace DbStatus {
    interface Raw {
        status_code: number;
        status_message: string;
    }
}
