/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as PromptonApi from "../../api";
import * as core from "../../core";
export declare const DefaultPostResponse: core.serialization.ObjectSchema<serializers.DefaultPostResponse.Raw, PromptonApi.DefaultPostResponse>;
export declare namespace DefaultPostResponse {
    interface Raw {
        id: string;
    }
}
