/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as PromptonApi from "../../api";
import * as core from "../../core";
export declare const FeedbackRead: core.serialization.ObjectSchema<serializers.FeedbackRead.Raw, PromptonApi.FeedbackRead>;
export declare namespace FeedbackRead {
    interface Raw {
        _id: string;
        created_at: string;
        created_by_user_id: string;
        created_by_org_id: string;
        inference_id: string;
        end_user_id?: string | null;
        feedback_for_part?: string | null;
        score?: number | null;
        flag?: string | null;
        note?: string | null;
        metadata?: Record<string, unknown> | null;
        prompt_version_id?: string | null;
    }
}
