/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as PromptonApi from "../../api";
import * as core from "../../core";
export declare const HttpValidationError: core.serialization.ObjectSchema<serializers.HttpValidationError.Raw, PromptonApi.HttpValidationError>;
export declare namespace HttpValidationError {
    interface Raw {
        detail?: serializers.ValidationError.Raw[] | null;
    }
}
