/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as PromptonApi from "../../api";
import * as core from "../../core";
export declare const InferenceError: core.serialization.ObjectSchema<serializers.InferenceError.Raw, PromptonApi.InferenceError>;
export declare namespace InferenceError {
    interface Raw {
        error_class: string;
        message: string;
        details?: unknown | null;
    }
}
