/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as PromptonApi from "../../api";
import * as core from "../../core";
export declare const InferencePostResponseResponse: core.serialization.Schema<serializers.InferencePostResponseResponse.Raw, PromptonApi.InferencePostResponseResponse>;
export declare namespace InferencePostResponseResponse {
    type Raw = serializers.InferenceResponseData.Raw | serializers.InferenceResponseError.Raw;
}
