/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as PromptonApi from "../../api";
import * as core from "../../core";
export declare const InferenceRead: core.serialization.ObjectSchema<serializers.InferenceRead.Raw, PromptonApi.InferenceRead>;
export declare namespace InferenceRead {
    interface Raw {
        _id: string;
        created_at: string;
        created_by_user_id: string;
        created_by_org_id: string;
        end_user_id?: string | null;
        source?: string | null;
        client_ref_id?: string | null;
        template_args: Record<string, string>;
        metadata?: Record<string, unknown> | null;
        request_timeout?: number | null;
        prompt_version_id: string;
        prompt_version_ids_considered: string[];
        prompt_id: string;
        prompt_version_name: string;
        status: serializers.InferenceResponseStatus.Raw;
        request: serializers.InferenceRequestData.Raw;
        response?: serializers.InferenceReadResponse.Raw | null;
    }
}
