/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as PromptonApi from "../../api";
import * as core from "../../core";
export declare const InferenceRequestData: core.serialization.ObjectSchema<serializers.InferenceRequestData.Raw, PromptonApi.InferenceRequestData>;
export declare namespace InferenceRequestData {
    interface Raw {
        provider: serializers.PromptVersionProviders.Raw;
        raw_request: serializers.ChatGptChatCompletitionRequest.Raw;
    }
}
