"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || function (mod) {
    if (mod && mod.__esModule) return mod;
    var result = {};
    if (mod != null) for (var k in mod) if (k !== "default" && Object.prototype.hasOwnProperty.call(mod, k)) __createBinding(result, mod, k);
    __setModuleDefault(result, mod);
    return result;
};
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.InferenceRead = void 0;
const core = __importStar(require("../../core"));
exports.InferenceRead = core.serialization.object({
    id: core.serialization.property("_id", core.serialization.string().optional()),
    createdAt: core.serialization.property("created_at", core.serialization.string().optional()),
    createdByUserId: core.serialization.property("created_by_user_id", core.serialization.string().optional()),
    createdByOrgId: core.serialization.property("created_by_org_id", core.serialization.string().optional()),
    endUserId: core.serialization.property("end_user_id", core.serialization.string().optional()),
    source: core.serialization.string().optional(),
    clientRefId: core.serialization.property("client_ref_id", core.serialization.string().optional()),
    templateArgs: core.serialization.property("template_args", core.serialization.record(core.serialization.string(), core.serialization.string()).optional()),
    metadata: core.serialization.record(core.serialization.string(), core.serialization.unknown()).optional(),
    requestTimeout: core.serialization.property("request_timeout", core.serialization.number().optional()),
    promptVersionId: core.serialization.property("prompt_version_id", core.serialization.string()),
    promptVersionIdsConsidered: core.serialization.property("prompt_version_ids_considered", core.serialization.list(core.serialization.string()).optional()),
    promptId: core.serialization.property("prompt_id", core.serialization.string()),
    promptVersionName: core.serialization.property("prompt_version_name", core.serialization.string().optional()),
    status: core.serialization.lazy(() => __awaiter(void 0, void 0, void 0, function* () { return (yield Promise.resolve().then(() => __importStar(require("..")))).InferenceResponseStatus; })).optional(),
    request: core.serialization.lazyObject(() => __awaiter(void 0, void 0, void 0, function* () { return (yield Promise.resolve().then(() => __importStar(require("..")))).InferenceRequestData; })).optional(),
    response: core.serialization.lazy(() => __awaiter(void 0, void 0, void 0, function* () { return (yield Promise.resolve().then(() => __importStar(require("..")))).InferenceReadResponse; })).optional(),
});
