/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as PromptonApi from "../../api";
import * as core from "../../core";
export declare const InferenceResponseData: core.serialization.ObjectSchema<serializers.InferenceResponseData.Raw, PromptonApi.InferenceResponseData>;
export declare namespace InferenceResponseData {
    interface Raw {
        completed_at?: string | null;
        completition_duration_seconds?: number | null;
        is_client_connected_at_finish?: boolean | null;
        isError?: boolean | null;
        token_usage: serializers.ChatGptTokenUsage.Raw;
        raw_response: serializers.ChatGptChatCompletitionResponse.Raw;
    }
}
