/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as PromptonApi from "../../api";
import * as core from "../../core";
export declare const InferencePostResponse: core.serialization.ObjectSchema<serializers.InferencePostResponse.Raw, PromptonApi.InferencePostResponse>;
export declare namespace InferencePostResponse {
    interface Raw {
        id: string;
        response: serializers.InferencePostResponseResponse.Raw;
    }
}
