/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as PromptonApi from "../../api";
import * as core from "../../core";
export declare const InferenceResponseError: core.serialization.ObjectSchema<serializers.InferenceResponseError.Raw, PromptonApi.InferenceResponseError>;
export declare namespace InferenceResponseError {
    interface Raw {
        completed_at?: string | null;
        completition_duration_seconds?: number | null;
        is_client_connected_at_finish?: boolean | null;
        isError?: boolean | null;
        error?: unknown | null;
    }
}
