/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as PromptonApi from "../../api";
import * as core from "../../core";
export declare const InferenceReadResponse: core.serialization.Schema<serializers.InferenceReadResponse.Raw, PromptonApi.InferenceReadResponse>;
export declare namespace InferenceReadResponse {
    type Raw = serializers.InferenceResponseData.Raw | serializers.InferenceResponseError.Raw;
}
