/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as PromptonApi from "../../api";
import * as core from "../../core";
export declare const PromptVersionProviders: core.serialization.Schema<serializers.PromptVersionProviders.Raw, PromptonApi.PromptVersionProviders>;
export declare namespace PromptVersionProviders {
    type Raw = "OpenAI";
}
