/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as PromptonApi from "../../api";
import * as core from "../../core";
export declare const PromptStatus: core.serialization.Schema<serializers.PromptStatus.Raw, PromptonApi.PromptStatus>;
export declare namespace PromptStatus {
    type Raw = "Active" | "Archived";
}
