/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as PromptonApi from "../../api";
import * as core from "../../core";
export declare const PromptVersionRead: core.serialization.ObjectSchema<serializers.PromptVersionRead.Raw, PromptonApi.PromptVersionRead>;
export declare namespace PromptVersionRead {
    interface Raw {
        _id?: string | null;
        created_at?: string | null;
        created_by_user_id?: string | null;
        created_by_org_id?: string | null;
        status?: serializers.PromptVersionStatus.Raw | null;
        provider?: serializers.PromptVersionProviders.Raw | null;
        name: string;
        description?: string | null;
        prompt_id: string;
        template?: serializers.ChatGptMessage.Raw[] | null;
        model_config?: serializers.ChatGptChatCompletitionConfig.Raw | null;
        template_arg_names?: string[] | null;
    }
}
