/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as PromptonApi from "../../api";
import * as core from "../../core";
export declare const Token: core.serialization.ObjectSchema<serializers.Token.Raw, PromptonApi.Token>;
export declare namespace Token {
    interface Raw {
        access_token: string;
        token_type: string;
    }
}
