/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as PromptonApi from "../../api";
import * as core from "../../core";
export declare const UserRead: core.serialization.ObjectSchema<serializers.UserRead.Raw, PromptonApi.UserRead>;
export declare namespace UserRead {
    interface Raw {
        _id?: string | null;
        created_at?: string | null;
        created_by_user_id?: string | null;
        created_by_org_id?: string | null;
        full_name?: string | null;
        disabled?: boolean | null;
        role?: serializers.UserRoles.Raw | null;
        org_id: string;
        email: string;
    }
}
