/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as PromptonApi from "../../api";
import * as core from "../../core";
export declare const UserRoles: core.serialization.Schema<serializers.UserRoles.Raw, PromptonApi.UserRoles>;
export declare namespace UserRoles {
    type Raw = "Basic" | "PromptAdmin" | "OrgAdmin" | "SuperAdmin";
}
