/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "..";
import * as PromptonApi from "../../api";
import * as core from "../../core";
export declare const ValidationErrorLocItem: core.serialization.Schema<serializers.ValidationErrorLocItem.Raw, PromptonApi.ValidationErrorLocItem>;
export declare namespace ValidationErrorLocItem {
    type Raw = string | number;
}
