/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as PromptonApi from "../../../../api";
import * as core from "../../../../core";
export declare const Response: core.serialization.Schema<serializers.promptVersions.getPromptVersionsList.Response.Raw, PromptonApi.PromptVersionRead[]>;
export declare namespace Response {
    type Raw = serializers.PromptVersionRead.Raw[];
}
