/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as PromptonApi from "../../../..";
export interface UserCreate {
    /** `non-empty` */
    fullName?: string;
    disabled?: boolean;
    role?: PromptonApi.UserRoles;
    orgId: string;
    email: string;
    /** `non-empty` */
    plainPassword: string;
}
