/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as PromptonApi from "../../../..";
export interface UserCreate {
    /** <span style="white-space: nowrap">`non-empty`</span> */
    fullName?: string;
    disabled?: boolean;
    role?: PromptonApi.UserRoles;
    orgId: string;
    email: string;
    /** <span style="white-space: nowrap">`non-empty`</span> */
    plainPassword: string;
}
