/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as PromptonApi from "..";
export interface ApiStatusResponse {
    version: string;
    message: string;
    dbstatus: PromptonApi.DbStatus;
    githubSha?: string;
    githubEnv?: string;
}
