/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface BodyGetAccessTokenExtendedTokenPost {
    grantType?: string;
    username: string;
    password: string;
    scope?: string;
    clientId?: string;
    clientSecret?: string;
}
