/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as PromptonApi from "..";
export interface ChatGptCompletitionChoice {
    message: PromptonApi.ChatGptMessage;
    finishReason: string;
    index: number;
}
