/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as PromptonApi from "..";
export interface ChatGptChatCompletitionResponse {
    id: string;
    object: string;
    created: number;
    model: string;
    usage: PromptonApi.ChatGptTokenUsage;
    choices: PromptonApi.ChatGptCompletitionChoice[];
}
