/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as PromptonApi from "..";
export interface ChatGptMessage {
    role: PromptonApi.ChatGptRole;
    content: string;
    name?: string;
}
