"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ChatGptRole = void 0;
exports.ChatGptRole = {
    System: "system",
    User: "user",
    Assistant: "assistant",
};
