/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * An enumeration.
 */
export declare type ChatGptRole = "system" | "user" | "assistant";
export declare const ChatGptRole: {
    readonly System: "system";
    readonly User: "user";
    readonly Assistant: "assistant";
};
