/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Standard response for POST requests. Contains the id of the created item.
 */
export interface DefaultPostResponse {
    /** The id of the created item */
    id: string;
}
