"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.InferenceResponseStatus = void 0;
exports.InferenceResponseStatus = {
    RequestReceived: "RequestReceived",
    Processed: "Processed",
    CompletitionError: "CompletitionError",
    CompletitionTimeout: "CompletitionTimeout",
};
