/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as PromptonApi from "..";
/**
 * Used for FastAPI response model
 */
export interface InferencePostResponse {
    id: string;
    response: PromptonApi.InferencePostResponseResponse;
}
