/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface InferenceCreateByPromptVersionId {
    /** <span style="white-space: nowrap">`non-empty`</span> */
    endUserId: string;
    /** <span style="white-space: nowrap">`non-empty`</span> */
    source: string;
    templateArgs?: Record<string, string>;
    metadata?: Record<string, unknown>;
    requestTimeout?: number;
    promptVersionId: string;
}
