/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as PromptonApi from "..";
export interface InferenceRead {
    id?: string;
    createdAt?: string;
    createdByUserId?: string;
    createdByOrgId?: string;
    /** `non-empty` */
    endUserId: string;
    /** `non-empty` */
    source: string;
    templateArgs?: Record<string, string>;
    metadata?: Record<string, unknown>;
    requestTimeout?: number;
    promptVersionId: string;
    promptId: string;
    promptVersionName?: string;
    status?: PromptonApi.InferenceResponseStatus;
    request?: PromptonApi.InferenceRequestData;
    response?: PromptonApi.InferenceReadResponse;
}
