/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as PromptonApi from "..";
export interface InferenceRequestData {
    provider: PromptonApi.PromptVersionProviders;
    rawRequest: PromptonApi.ChatGptChatCompletitionRequest;
}
