/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * An enumeration.
 */
export declare type InferenceResponseStatus = "RequestReceived" | "Processed" | "CompletitionError" | "CompletitionTimeout";
export declare const InferenceResponseStatus: {
    readonly RequestReceived: "RequestReceived";
    readonly Processed: "Processed";
    readonly CompletitionError: "CompletitionError";
    readonly CompletitionTimeout: "CompletitionTimeout";
};
