/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as PromptonApi from "..";
export interface InferenceRead {
    id?: string;
    createdAt?: string;
    createdByUserId?: string;
    createdByOrgId?: string;
    /** <span style="white-space: nowrap">`non-empty`</span> */
    endUserId: string;
    /** <span style="white-space: nowrap">`non-empty`</span> */
    source: string;
    templateArgs?: Record<string, string>;
    metadata?: Record<string, unknown>;
    requestTimeout?: number;
    promptVersionId: string;
    /** If inference was by prompt_id then a list of all other prompt versions considered for this inference. I.e. all prompt versions in Live status at the time of the inference */
    promptVersionIdsConsidered?: string[];
    promptId: string;
    promptVersionName?: string;
    status?: PromptonApi.InferenceResponseStatus;
    request?: PromptonApi.InferenceRequestData;
    response?: PromptonApi.InferenceReadResponse;
}
