/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Create inference by `prompt_id`. It can only be used if there is at least one 'Live' status prompt version for the provided `prompt_id`.
 * If there are multiple prompt versions in Live status it will pick one randomly. Useful for split testing prompt versions.
 * It stores all other `prompt_version_id`s in Live status at the time of the inference in `prompt_version_ids_considered` field.
 */
export interface InferenceCreateByPromptId {
    /** <span style="white-space: nowrap">`non-empty`</span> */
    endUserId: string;
    /** <span style="white-space: nowrap">`non-empty`</span> */
    source: string;
    templateArgs?: Record<string, string>;
    metadata?: Record<string, unknown>;
    requestTimeout?: number;
    promptId: string;
}
