/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface InferenceResponseError {
    completedAt?: string;
    completitionDurationSeconds?: number;
    isClientConnectedAtFinish?: boolean;
    isError?: boolean;
    error?: unknown;
}
