/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as PromptonApi from "..";
/**
 * Base model for reading from MongoDB. Same as MongoBaseCreate but assumes all DB base fields are populated so generated clients doesn't requrie None checks
 */
export interface InferenceRead {
    id: string;
    createdAt: string;
    createdByUserId: string;
    createdByOrgId: string;
    /** The API consumer's internal user reference for metrics. It is also relayed to the provider as part of the request if the provider supports it (eg. OpenAI's user field). */
    endUserId?: string;
    /** The API consumer's source for metrics (e.g. AndroidApp etc). */
    source?: string;
    /** The API consumer's internal reference id to able to link references to their sessions. */
    clientRefId?: string;
    templateArgs: Record<string, string>;
    metadata?: Record<string, unknown>;
    /** Provider request timout in seconds. If not provided, then Prompton API's default timeout for the provider will be used (90sec or `DEFAULT_OPENAI_REQUEST_TIMEOUT_SECONDS` env var if provided). */
    requestTimeout?: number;
    promptVersionId: string;
    promptVersionIdsConsidered: string[];
    promptId: string;
    promptVersionName: string;
    status: PromptonApi.InferenceResponseStatus;
    request: PromptonApi.InferenceRequestData;
    response?: PromptonApi.InferenceReadResponse;
}
