/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as PromptonApi from "..";
export declare type InferencePostResponseResponse = PromptonApi.InferenceResponseData | PromptonApi.InferenceResponseError;
