/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Base model for reading from MongoDB. Same as MongoBaseCreate but assumes all DB base fields are populated so generated clients doesn't requrie None checks
 */
export interface OrgRead {
    id: string;
    createdAt: string;
    createdByUserId: string;
    createdByOrgId: string;
    name: string;
    accessKeys?: Record<string, string>;
}
