/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * An enumeration.
 */
export declare type PromptStatus = "Active" | "Archived";
export declare const PromptStatus: {
    readonly Active: "Active";
    readonly Archived: "Archived";
};
