/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * Currently only OpenAI is supported
 */
export declare type PromptVersionProviders = "OpenAI";
export declare const PromptVersionProviders: {
    readonly OpenAi: "OpenAI";
};
