/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as PromptonApi from "..";
/**
 * Base model for reading from MongoDB. Same as MongoBaseCreate but assumes all DB base fields are populated so generated clients doesn't requrie None checks
 */
export interface PromptVersionRead {
    id: string;
    createdAt: string;
    createdByUserId: string;
    createdByOrgId: string;
    status: PromptonApi.PromptVersionStatus;
    provider: PromptonApi.PromptVersionProviders;
    /** <span style="white-space: nowrap">`non-empty`</span> */
    name: string;
    description?: string;
    promptId: string;
    template: PromptonApi.ChatGptMessage[];
    modelConfig?: PromptonApi.ChatGptChatCompletitionConfig;
    /** List of args in the template - populated by server at PATHC and POST */
    templateArgNames: string[];
}
