"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PromptVersionStatus = void 0;
exports.PromptVersionStatus = {
    Draft: "Draft",
    Testing: "Testing",
    Live: "Live",
    Archived: "Archived",
};
