/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as PromptonApi from "..";
export interface PromptRead {
    id?: string;
    createdAt?: string;
    createdByUserId?: string;
    createdByOrgId?: string;
    status?: PromptonApi.PromptStatus;
    /** <span style="white-space: nowrap">`non-empty`</span> */
    name: string;
    description?: string;
}
