/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * An enumeration.
 */
export declare type PromptVersionStatus = "Draft" | "Testing" | "Live" | "Archived";
export declare const PromptVersionStatus: {
    readonly Draft: "Draft";
    readonly Testing: "Testing";
    readonly Live: "Live";
    readonly Archived: "Archived";
};
