"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.UserRoles = void 0;
exports.UserRoles = {
    Basic: "Basic",
    OrgAdmin: "OrgAdmin",
    SuperAdmin: "SuperAdmin",
};
