/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as PromptonApi from "..";
export interface UserRead {
    id?: string;
    createdAt?: string;
    createdByUserId?: string;
    createdByOrgId?: string;
    /** `non-empty` */
    fullName?: string;
    disabled?: boolean;
    role?: PromptonApi.UserRoles;
    orgId: string;
    email: string;
}
