/**
 * This file was auto-generated by Fern from our API Definition.
 */
/**
 * An enumeration.
 */
export declare type UserRoles = "Basic" | "PromptAdmin" | "OrgAdmin" | "SuperAdmin";
export declare const UserRoles: {
    readonly Basic: "Basic";
    readonly PromptAdmin: "PromptAdmin";
    readonly OrgAdmin: "OrgAdmin";
    readonly SuperAdmin: "SuperAdmin";
};
