# Client SDK generation scripts
# TODO: clean and build all clients before generating

default: 
  just --list

install:
  npm install

# updates openapi.yml from server/generated and generates clients with fern
generate-clients:
  cp ../server/generated/openapi/openapi.yml fern/api/openapi
  npx fern generate