/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as PromptonApi from "../../../..";
export interface PromptUpdate {
    status?: PromptonApi.PromptStatus;
    /** `non-empty` */
    name?: string;
    description?: string;
}
