/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../..";
import * as PromptonApi from "../../../../api";
import * as core from "../../../../core";
export declare const Response: core.serialization.Schema<serializers.feedbacks.getFeedbacksList.Response.Raw, PromptonApi.FeedbackRead[]>;
export declare namespace Response {
    type Raw = serializers.FeedbackRead.Raw[];
}
