/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../..";
import * as PromptonApi from "../../../../../api";
import * as core from "../../../../../core";
export declare const InferenceCreate: core.serialization.Schema<serializers.InferenceCreate.Raw, PromptonApi.InferenceCreate>;
export declare namespace InferenceCreate {
    interface Raw {
        end_user_id: string;
        source: string;
        template_args?: Record<string, string> | null;
        metadata?: Record<string, unknown> | null;
        request_timeout?: number | null;
        prompt_version_id: string;
    }
}
