# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class PromptStatus(str, enum.Enum):
    """
    An enumeration.
    """

    ACTIVE = "Active"
    ARCHIVED = "Archived"

    def visit(self, active: typing.Callable[[], T_Result], archived: typing.Callable[[], T_Result]) -> T_Result:
        if self is PromptStatus.ACTIVE:
            return active()
        if self is PromptStatus.ARCHIVED:
            return archived()
