/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../..";
import * as PromptonApi from "../../../../../api";
import * as core from "../../../../../core";
export declare const PromptVersionUpdate: core.serialization.Schema<serializers.PromptVersionUpdate.Raw, PromptonApi.PromptVersionUpdate>;
export declare namespace PromptVersionUpdate {
    interface Raw {
        status?: serializers.PromptVersionStatus.Raw | null;
        provider?: serializers.PromptVersionProviders.Raw | null;
        name?: string | null;
        description?: string | null;
        prompt_id?: string | null;
        template?: serializers.ChatGptMessage.Raw[] | null;
        model_config?: serializers.ChatGptChatCompletitionConfig.Raw | null;
    }
}
