/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../..";
import * as PromptonApi from "../../../../../api";
import * as core from "../../../../../core";
export declare const PromptVersionCreate: core.serialization.Schema<serializers.PromptVersionCreate.Raw, PromptonApi.PromptVersionCreate>;
export declare namespace PromptVersionCreate {
    interface Raw {
        status?: serializers.PromptVersionStatus.Raw | null;
        provider?: serializers.PromptVersionProviders.Raw | null;
        name: string;
        description?: string | null;
        prompt_id: string;
        template?: serializers.ChatGptMessage.Raw[] | null;
        model_config?: serializers.ChatGptChatCompletitionConfig.Raw | null;
    }
}
