/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as PromptonApi from "../../../..";
export interface PromptVersionUpdate {
    status?: PromptonApi.PromptVersionStatus;
    provider?: PromptonApi.PromptVersionProviders;
    /** `non-empty` */
    name?: string;
    description?: string;
    promptId?: string;
    template?: PromptonApi.ChatGptMessage[];
    modelConfig?: PromptonApi.ChatGptChatCompletitionConfig;
}
