/**
 * prompton-api
 * API for prompton - managing full lifecycle of AI chat prompts.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { PromptStatus } from './promptStatus';

export class PromptRead {
    'id'?: string;
    'createdAt'?: Date;
    'createdByUserId'?: string;
    'createdByOrgId'?: string;
    'status'?: PromptStatus;
    'name': string;
    'description'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "_id",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date"
        },
        {
            "name": "createdByUserId",
            "baseName": "created_by_user_id",
            "type": "string"
        },
        {
            "name": "createdByOrgId",
            "baseName": "created_by_org_id",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "PromptStatus"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return PromptRead.attributeTypeMap;
    }
}

export namespace PromptRead {
}
