/**
 * prompton-api
 * API for prompton - managing full lifecycle of AI chat prompts.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ChatGPTChatCompletitionResponse } from './chatGPTChatCompletitionResponse';
import { ChatGPTTokenUsage } from './chatGPTTokenUsage';
import { InferenceResponseData } from './inferenceResponseData';
import { InferenceResponseError } from './inferenceResponseError';

export class Response {
    'completedAt'?: Date;
    'completitionDurationSeconds'?: number;
    'isClientConnectedAtFinish'?: boolean;
    'isError'?: boolean = true;
    'tokenUsage': ChatGPTTokenUsage;
    'rawResponse': ChatGPTChatCompletitionResponse;
    'error'?: any | null;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "completedAt",
            "baseName": "completed_at",
            "type": "Date"
        },
        {
            "name": "completitionDurationSeconds",
            "baseName": "completition_duration_seconds",
            "type": "number"
        },
        {
            "name": "isClientConnectedAtFinish",
            "baseName": "is_client_connected_at_finish",
            "type": "boolean"
        },
        {
            "name": "isError",
            "baseName": "isError",
            "type": "boolean"
        },
        {
            "name": "tokenUsage",
            "baseName": "token_usage",
            "type": "ChatGPTTokenUsage"
        },
        {
            "name": "rawResponse",
            "baseName": "raw_response",
            "type": "ChatGPTChatCompletitionResponse"
        },
        {
            "name": "error",
            "baseName": "error",
            "type": "any"
        }    ];

    static getAttributeTypeMap() {
        return Response.attributeTypeMap;
    }
}

