/**
 * prompton-api
 * API for prompton - managing full lifecycle of AI chat prompts.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* An enumeration.
*/
export enum UserRoles {
    Basic = <any> 'Basic',
    OrgAdmin = <any> 'OrgAdmin',
    SuperAdmin = <any> 'SuperAdmin'
}
