/**
 * prompton-api
 * API for prompton - managing full lifecycle of AI chat prompts.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { UserRoles } from './userRoles';

export class UserRead {
    'id'?: string;
    'createdAt'?: Date;
    'createdByUserId'?: string;
    'createdByOrgId'?: string;
    'fullName'?: string;
    'disabled'?: boolean = false;
    'role'?: UserRoles;
    'orgId': string;
    'email': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "_id",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date"
        },
        {
            "name": "createdByUserId",
            "baseName": "created_by_user_id",
            "type": "string"
        },
        {
            "name": "createdByOrgId",
            "baseName": "created_by_org_id",
            "type": "string"
        },
        {
            "name": "fullName",
            "baseName": "full_name",
            "type": "string"
        },
        {
            "name": "disabled",
            "baseName": "disabled",
            "type": "boolean"
        },
        {
            "name": "role",
            "baseName": "role",
            "type": "UserRoles"
        },
        {
            "name": "orgId",
            "baseName": "org_id",
            "type": "string"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return UserRead.attributeTypeMap;
    }
}

export namespace UserRead {
}
