/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface OrgCreate {
    /** <span style="white-space: nowrap">`non-empty`</span> */
    name: string;
    accessKeys?: Record<string, string>;
}
