/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface InferenceCreate {
    /** `non-empty` */
    endUserId: string;
    /** `non-empty` */
    source: string;
    templateArgs?: Record<string, string>;
    metadata?: Record<string, unknown>;
    requestTimeout?: number;
    promptVersionId: string;
}
