/**
 * This file was auto-generated by Fern from our API Definition.
 */
export interface GetFeedbacksListRequest {
    promptVersionId?: string;
    promptonUserId?: string;
    inferenceId?: string;
}
