/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "./core";
import { ServerStatus } from "./api/resources/serverStatus/client/Client";
import { Authentication } from "./api/resources/authentication/client/Client";
import { Prompts } from "./api/resources/prompts/client/Client";
import { PromptVersions } from "./api/resources/promptVersions/client/Client";
import { Inferences } from "./api/resources/inferences/client/Client";
import { Orgs } from "./api/resources/orgs/client/Client";
import { Users } from "./api/resources/users/client/Client";
export declare namespace PromptonApiClient {
    interface Options {
        environment: string;
        token?: core.Supplier<core.BearerToken | undefined>;
    }
}
export declare class PromptonApiClient {
    protected readonly options: PromptonApiClient.Options;
    constructor(options: PromptonApiClient.Options);
    protected _serverStatus: ServerStatus | undefined;
    get serverStatus(): ServerStatus;
    protected _authentication: Authentication | undefined;
    get authentication(): Authentication;
    protected _prompts: Prompts | undefined;
    get prompts(): Prompts;
    protected _promptVersions: PromptVersions | undefined;
    get promptVersions(): PromptVersions;
    protected _inferences: Inferences | undefined;
    get inferences(): Inferences;
    protected _orgs: Orgs | undefined;
    get orgs(): Orgs;
    protected _users: Users | undefined;
    get users(): Users;
}
