/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as core from "../../../../core";
import * as PromptonApi from "../../..";
export declare namespace ServerStatus {
    interface Options {
        environment: core.Supplier<string>;
        token?: core.Supplier<core.BearerToken | undefined>;
    }
}
export declare class ServerStatus {
    protected readonly _options: ServerStatus.Options;
    constructor(_options: ServerStatus.Options);
    getStatus(): Promise<PromptonApi.ApiStatusResponse>;
    protected _getAuthorizationHeader(): Promise<string | undefined>;
}
