/**
 * This file was auto-generated by Fern from our API Definition.
 */
import * as serializers from "../../../..";
import * as PromptonApi from "../../../../../api";
import * as core from "../../../../../core";
export declare const FeedbackCreate: core.serialization.Schema<serializers.FeedbackCreate.Raw, PromptonApi.FeedbackCreate>;
export declare namespace FeedbackCreate {
    interface Raw {
        inference_id: string;
        end_user_id?: string | null;
        feedback_for_part?: string | null;
        score?: number | null;
        flag?: string | null;
        note?: string | null;
        metadata?: Record<string, unknown> | null;
    }
}
