"use strict";
/**
 * This file was auto-generated by Fern from our API Definition.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.PromptonApiTimeoutError = void 0;
class PromptonApiTimeoutError extends Error {
    constructor() {
        super("Timeout");
        Object.setPrototypeOf(this, PromptonApiTimeoutError.prototype);
    }
}
exports.PromptonApiTimeoutError = PromptonApiTimeoutError;
