# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: CI

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      MONGO_INITDB_DATABASE: ${{ vars.MONGO_INITDB_DATABASE }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11.3
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.3"
          cache: "poetry"
      - name: Install pipenv
        run: pip install poetry
      - name: Install packages
        run: poetry install --dev
      - name: Run tests
        run: poetry run pytest
