# See more: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
name: Server Tests

defaults:
  run:
    working-directory: server

on:
  pull_request:
    paths: "server/**"
  push:
    paths: "server/**"

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          sparse-checkout: "server/"

      - name: create .env file
        run: |
          echo "DATABASE_URL=dummy" >> .env
          echo "MONGO_DATABASE=dummy" >> .env
          echo "JWT_SECRET_KEY=dummy" >> .env

      - name: Install poetry
        run: pipx install poetry

      - name: Debug info
        run: |
          ls -la
          pwd
          echo "github.workspace: ${{ github.workspace }}"

      - name: Set up Python 3.11.3
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.3"
          cache: "poetry"

      - name: Install packages
        run: poetry install

      - name: Run pytest
        run: poetry run pytest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build docker image
        uses: docker/build-push-action@v4
        with:
          context: server
          file: ./server/Dockerfile
          tags: "citest"
          push: false
          load: true

      - name: Launch Docker container for test
        run: docker run --env-file .env -p 8080:8080 --rm --detach "citest"

      # - name: Wait for server to be ready
      #   uses: cygnetdigital/wait_for_response@v2.0.0
      #   with:
      #     url: "http://localhost:8080/"

      # - name: Check if container responsive
      #   uses: iFaxity/wait-on-action@v1.1.0
      #   with:
      #     resource: http://localhost:8080

      - name: Wait for server to be ready
        run: |
          while ! curl http://localhost:8080  do
            echo "Waiting for server..."
            sleep 5
          done
