# See more: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Server Tests

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: staging

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      MONGO_DATABASE: ${{ vars.MONGO_DATABASE }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}

    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry

      - name: Set up Python 3.11.3
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.3"
          cache: "poetry"

      - name: Install packages
        run: poetry install

      - name: Run pytest
        run: poetry run pytest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: false
